import { Language } from './types';

export const LANGUAGES: Language[] = [
  { id: 'python', name: 'Python', category: 'Backend', description: 'Versatile, readable language for web, data, and AI.' },
  { id: 'javascript', name: 'JavaScript', category: 'Frontend', description: 'The language of the web.' },
  { id: 'typescript', name: 'TypeScript', category: 'Frontend', description: 'JavaScript with syntax for types.' },
  { id: 'java', name: 'Java', category: 'Backend', description: 'Robust, object-oriented language for enterprise.' },
  { id: 'cpp', name: 'C++', category: 'Systems', description: 'High-performance system programming.' },
  { id: 'csharp', name: 'C#', category: 'Backend', description: 'Modern language for Windows and game dev.' },
  { id: 'php', name: 'PHP', category: 'Backend', description: 'Server-side scripting for web development.' },
  { id: 'swift', name: 'Swift', category: 'Mobile', description: 'Apple\'s language for iOS and macOS.' },
  { id: 'go', name: 'Go', category: 'Backend', description: 'Efficient, concurrent language by Google.' },
  { id: 'rust', name: 'Rust', category: 'Systems', description: 'Safe, concurrent system programming.' },
  { id: 'ruby', name: 'Ruby', category: 'Backend', description: 'Focus on simplicity and productivity.' },
  { id: 'kotlin', name: 'Kotlin', category: 'Mobile', description: 'Modern language for Android development.' },
  { id: 'sql', name: 'SQL', category: 'Data Science', description: 'Standard language for relational databases.' },
  { id: 'html', name: 'HTML', category: 'Frontend', description: 'Markup for the web.' },
  { id: 'css', name: 'CSS', category: 'Frontend', description: 'Styling for the web.' },
  { id: 'r', name: 'R', category: 'Data Science', description: 'Statistical computing and graphics.' },
  { id: 'matlab', name: 'MATLAB', category: 'Data Science', description: 'Numerical computing environment.' },
  { id: 'scala', name: 'Scala', category: 'Backend', description: 'Functional and object-oriented on JVM.' },
  { id: 'perl', name: 'Perl', category: 'Other', description: 'Text processing and system admin.' },
  { id: 'haskell', name: 'Haskell', category: 'Other', description: 'Purely functional programming.' },
  { id: 'lua', name: 'Lua', category: 'Other', description: 'Lightweight scripting language.' },
  { id: 'dart', name: 'Dart', category: 'Mobile', description: 'Client-optimized for fast apps (Flutter).' },
  { id: 'objc', name: 'Objective-C', category: 'Mobile', description: 'Legacy Apple programming language.' },
  { id: 'asm', name: 'Assembly', category: 'Systems', description: 'Low-level machine code.' },
  { id: 'shell', name: 'Shell', category: 'Systems', description: 'Command-line scripting.' },
  { id: 'groovy', name: 'Groovy', category: 'Backend', description: 'Dynamic language for JVM.' },
  { id: 'delphi', name: 'Delphi', category: 'Other', description: 'Object Pascal for rapid app dev.' },
  { id: 'vb', name: 'Visual Basic', category: 'Other', description: 'Legacy Microsoft language.' },
  { id: 'fortran', name: 'Fortran', category: 'Other', description: 'Scientific and engineering computing.' },
  { id: 'cobol', name: 'COBOL', category: 'Other', description: 'Legacy business applications.' },
  { id: 'ada', name: 'Ada', category: 'Systems', description: 'High-reliability system programming.' },
  { id: 'lisp', name: 'Lisp', category: 'Other', description: 'Pioneer of functional programming.' },
  { id: 'prolog', name: 'Prolog', category: 'Other', description: 'Logic programming language.' },
  { id: 'erlang', name: 'Erlang', category: 'Backend', description: 'Concurrent, fault-tolerant systems.' },
  { id: 'fsharp', name: 'F#', category: 'Other', description: 'Functional-first language for .NET.' },
  { id: 'clojure', name: 'Clojure', category: 'Other', description: 'Modern Lisp on the JVM.' },
  { id: 'elixir', name: 'Elixir', category: 'Backend', description: 'Dynamic, functional on Erlang VM.' },
  { id: 'julia', name: 'Julia', category: 'Data Science', description: 'High-performance technical computing.' },
  { id: 'nim', name: 'Nim', category: 'Systems', description: 'Efficient, expressive system language.' },
  { id: 'zig', name: 'Zig', category: 'Systems', description: 'Modern alternative to C.' },
  { id: 'crystal', name: 'Crystal', category: 'Backend', description: 'Ruby-like syntax with C performance.' },
  { id: 'smalltalk', name: 'Smalltalk', category: 'Other', description: 'Pure object-oriented language.' },
  { id: 'pascal', name: 'Pascal', category: 'Other', description: 'Influential structured programming.' },
  { id: 'scheme', name: 'Scheme', category: 'Other', description: 'Minimalist Lisp dialect.' },
  { id: 'verilog', name: 'Verilog', category: 'Systems', description: 'Hardware description language.' },
  { id: 'vhdl', name: 'VHDL', category: 'Systems', description: 'Hardware description language.' },
  { id: 'scratch', name: 'Scratch', category: 'Other', description: 'Block-based visual programming.' },
  { id: 'solidity', name: 'Solidity', category: 'Other', description: 'Smart contracts for Ethereum.' },
  { id: 'vyper', name: 'Vyper', category: 'Other', description: 'Pythonic smart contract language.' },
  { id: 'racket', name: 'Racket', category: 'Other', description: 'General-purpose Lisp dialect.' },
];

export const IT_CATEGORIES = [
  'Hardware', 'Operating Systems', 'Networking', 'Security', 'Cloud Computing',
  'Databases', 'Web Technologies', 'Software Engineering', 'AI & Machine Learning',
  'Data Science', 'DevOps', 'Mobile Development', 'Game Development', 'Blockchain'
];
